site_name: MSight Documentation
theme:
  name: material
  logo: assets/images/uofm.webp
  features:
    - navigation.sections
    - navigation.tabs
    - navigation.footer 
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - content.code.copy

  palette:
    - scheme: default          # Light mode
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    - scheme: slate            # Dark mode
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

extra_css:
  - styles/brand-colors.css
extra:
  generator: false
copyright: "© University of Michigan — Mcity & Michigan Mobility Transformation Lab"

nav:
  - Introduction: index.md
  - Getting Started: getting-started/quickstart.md
  - Installation:
    - Installation Overview: installation/index.md
    - Local Installation: installation/local.md
    - Docker Installation: installation/docker.md
  - System Architecture: 
    - Architecture Overview: architecture/index.md
    - Nodes: architecture/nodes.md
    - Data Types: architecture/data.md
    - Pub/Sub: architecture/pubsub.md
    - Security: architecture/security.md
  - Algorithms:
    - Algorithm Overview: algorithms/index.md
    - 2D Detection: algorithms/det2d.md
    - 3D Detection: algorithms/det3d.md
    - Sensor Fusion: algorithms/sensor-fusion.md
    - Prediction: algorithms/prediction.md
    - Near-miss Detection: algorithms/near-miss.md
  - Cloud Integration: 
    - Overview: cloud-integration/index.md
    - Minimum Setup Example with AWS Kinesis, Firehose and S3: cloud-integration/min-setup-kinesis.md
  - Security: security/
  - Deployment: deployment/
  - Tutorials: tutorials/
  - Developer Guide: developer-guide/

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
